name: Pact - Can I Deploy
description: Ask pact broker if we can deploy on specified environment
inputs:
  pacticipant:
    description: The pacticipant name, i.e. consumer name
    required: true
  version:
    description: The pacticipant version
    required: false
  tag:
    description: The tag version
    required: false
  to:
    description: The tag that represents the branch or environment of the integrated applications for which you want to check the verification result status.
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/pact-can-i-deploy.sh
      shell: bash
      env:
        PACTICIPANT: ${{ inputs.pacticipant }}
        TAG: ${{ inputs.tag }}
        TO: ${{ inputs.to }}
        VERSION: ${{ inputs.version }}