name: Pact - Can I Deploy
description: Ask pact broker if we can deploy on specified environment
inputs:
  pacticipant:
    description: The pacticipant name, i.e. consumer name
    required: true
  version:
    description: The pacticipant version
    required: true
  to:
    description: The tag that represents the branch or environment of the integrated applications for which you want to check the verification result status.
    required: true
  tag:
    description: Optionally specify a TAG to use the latest version with the specified tag.
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - broker
    - can-i-deploy
    - --pacticipant
    - ${{ inputs.pacticipant }}
    - --version
    - ${{ inputs.version }}
    - --to
    - ${{ inputs.to }}
    - --latest
    - ${{ input.tag }}
